/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id int generated by default as identity,
    name varchar(50),
    date_of_birth date,
    escape_attempts int,
    neutered boolean default false,
    weight_kg decimal
);

alter table animals add column species varchar ;

CREATE TABLE owners (
    id INT GENERATED ALWAYS AS IDENTITY,
    full_name VARCHAR(100),
    age INT,
    PRIMARY KEY(id)
);

CREATE TABLE species (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100),
    PRIMARY KEY(id)
);

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD COLUMN species_id INTEGER;

ALTER TABLE animals ADD COLUMN owner_id INTEGER;

ALTER TABLE animals ADD FOREIGN KEY (species_id) REFERENCES species (id);

ALTER TABLE animals ADD FOREIGN KEY (owner_id) REFERENCES owners (id);